{% set version = "1.3.0a04" %}
{% set sha256 = "73d105f050481a0bf470898c2e932cba102f617cd21f2e707128467ac4218eaa" %}

package:
  name: selscan
  version: {{ version }}

source:
  url: https://github.com/notestaff/selscan/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - make
  host:
    - gsl
    - zlib
    - boost=1.74.0
  run:
    - boost=1.74.0
    - gsl
    - zlib

test:
  commands:
    - selscan 2>&1 | grep -qF 'selscan'

about:
  home: https://github.com/szpiech/selscan
  license: GPL-3.0
  license_family: GPL
  summary: a program to calculate EHH-based scans for positive selection in genomes

extra:
  identifiers:
    - biotools:selscan
    - doi:10.1093/molbev/msu211
  skip-lints:
    - should_not_be_noarch_source
