terra:
  namespace: um1-encode-y2s1
  workspace: selection-sim
  gs_bucket: fc-21baddbc-5142-4983-a26e-7d85a72c830b
  users:
    - sgosai@broadinstitute.org
    - sreilly@broadinstitute.org
    - ilya@broadinstitute.org

  root_workflows:
    cms2_sim_data:
      wdl: cms2_main.wdl
      synopsis: run sims and compute component stats
      method_name: test-cosi2-method-01
      config_name: cms2-sim-data
      test_data: test.02.wdl.json

    cms2_emp_data:
      wdl: cms2_main_emp.wdl
      synopsis: fetch empirical data and compute component stats
      method_name: cosi2_test_01
      config_name: cms2-emp-data
      test_data: test.cms2_main_emp.wdl.json
