terra:
  namespace: um1-encode-y2s1
  workspace: selection-sim
  gs_bucket: fc-21baddbc-5142-4983-a26e-7d85a72c830b
  users:
    - sgosai@broadinstitute.org
    - sreilly@broadinstitute.org
    - ilya@broadinstitute.org
    - stephen.rong@yale.edu

  root_workflows:
    cms2_stdpopsim_ooa_archaic_admixture_test_sim_train_data_srong:
      skip: False
      wdl: cms2_main.wdl
      synopsis: run sims and compute component stats with iSAFE on stdpopsim ooa archaic admixture model
      method_name: test-cosi2-method-01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2_stdpopsim_ooa_archaic_admixture_test_sim_train_data_srong
      test_data: test.cms2_stdpopsim_ooa_archaic_admixture_test_sim_train_data_srong.wdl.json

    cms2_best_model_make_min_sim_train_data:
      skip: True
      wdl: cms2_main.wdl
      synopsis: run sims and compute component stats with iSAFE on original model
      method_name: test-cosi2-method-01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2_best_model_make_min_sim_train_data
      test_data: test.cms2_best_model_make_min_sim_train_data.wdl.json

    cms2_make_min_sim_train_data:
      skip: True
      wdl: cms2_main.wdl
      synopsis: run sims and compute component stats with iSAFE on original model
      method_name: test-cosi2-method-01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2_make_min_sim_train_data
      test_data: test.cms2_make_min_sim_train_data.wdl.json

    cms2_sim_data:
      skip: True
      wdl: cms2_main.wdl
      synopsis: run sims and compute component stats
      method_name: test-cosi2-method-01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2-sim-data
      test_data: test.02.wdl.json

    cms2_sim_isafe_orig:
      skip: True
      wdl: cms2_main.wdl
      synopsis: run sims and compute component stats with iSAFE on original model
      method_name: test-cosi2-method-01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2-sim-isafe-orig
      test_data: test.cms2_sim_isafe_orig.wdl.json

    # cms2_emp_data:
    #   wdl: cms2_main_emp.wdl
    #   synopsis: fetch empirical data and compute component stats
    #   method_name: cosi2_test_01
    #   config_name: cms2-emp-data
    #   test_data: test.cms2_main_emp.wdl.json

    cms2_empirical:
      skip: True
      wdl: cms2_empirical.wdl
      synopsis: fetch and analyze empirical data
      method_name: cosi2_test_01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2-empirical
      test_data: test.cms2_empirical.wdl.json

    cms2_empirical_isafe_test:
      skip: True
      wdl: cms2_empirical.wdl
      synopsis: fetch and analyze empirical data to test isafe
      method_name: cosi2_test_01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2-empirical-isafe-test
      test_data: test.cms2_empirical_isafe_test.wdl.json

    cms2_empirical_woerner18neutralome:
      skip: True
      wdl: cms2_empirical.wdl
      synopsis: fetch and analyze empirical data
      method_name: cosi2_test_01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2-empirical-woerner18neutralome
      test_data: test.cms2_empirical_woerner18neutralome.wdl.json

    cms2_test_fetch:
      skip: True
      wdl: cms2_test_fetch.wdl
      synopsis: test fetching of files
      method_name: cosi2_test_01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: cms2_test_fetch
      test_data: cms2_test_fetch.wdl.json

    cms2_construct_empirical_neutral_regions:
      skip: True
      wdl: empirical_neutral_regions.wdl
      synopsis: construct empirical neutral regions
      method_name: test-cosi2-method-01  # arbitrary until figure out how to create new methods in Terra workspace
      config_name: construct_empirical_neutral_regions
      test_data: test.construct_empirical_neutral_regions.wdl.json
