sudo: required

dist: focal
os: linux

git:
  depth: 5

services:
  - docker

env:
#  - LANGUAGE=cwl
  global:
    - LANGUAGE=wdl
  # GH_TOKEN
    - secure: "rdnFRFHOzBinOqgh9K4WmNS3s5j6gIgEoPFhfnwyVvgAghembl3srbPOYnGIYD9QQTetHcQ1qrN0DRDKLEBupDO7mugRhRg4nyZnfsW6qggefH1ypBnUGfdPp5yhaULmv5Rj9e70SZ8I+TeRcw0zhQ6vLlpEnT43K1enKpaiv/96xuff5MWvsjoT8bgHDRUdLomm1fdloSGs8xcaHzCLWDhJZpODiVIr+iKFb98vUVanDhptWcYxpZlPAPbeNdFLYqQO6rtWOriz9YkbHRYwIX/erJQd1h+9WBbmjwJCDYzHh2REjfPlK1OYyl9P69K5PqVvZ/dM6zDbEKvQqxuecVxV/+e0ymjUQQdITQ3lZG7iyn7Tfh0zTQruhk7x5CYUatG1T1uL2v1tVTBjyNRuZJyEPYGPnDr1eycfTxdQUkBBLsdYVZIDPCgVpaD41lNVM5Ti/TBVWl6E7e+jo8XYccAblj0763v8J0jPodCBClNcf8bN6fo0oWo8YLi8x9RRJ8G2zc6ROAAAjs4Hq25jg+n4QpBWOZMVyfYWRMSiAXJAo48Vx/3Ml7ITH4MWL5khaqZa0CaR9i6MAhecMcPsZ/hlpnDNX3D8/adluUTTD9LqZhtud1G1stK5h9zl1OuxToULDus2v3av9cbiJmFNz6oPigCpjmu7Kp1hGZLNNDs="
#  - LANGUAGE=nfl

branches:
  except:
    - /.*-staging$/

# notifications:
#   slack: 
#     on_success: never
#     on_failure: always
#     rooms:
#       - oicr:S9k4EowgQv9AnbCfEZHSzCsg

language: java
jdk: 
  - openjdk11

#before_install:
#  - docker build -t quay.io/ilya_broad/dockstore-tool-cosi2 .
#  - pyenv global 3.6

#install: 
#  - bash install.sh

script: 
  - bash script.sh
